# Generated by Django 4.2.1 on 2023-06-08 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
